config/routes.rb
Rails.application.routes.draw do
  
  resources :articles
  root 'pages#home'
  get 'about' , to:'pages#about'
  get 'signup',to:'users#new'
  resources :users, except: [:new]

  get 'login', to:"sessions#new"
  post 'login', to:"sessions#create"
  delete 'logout', to:"sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	belongs_to :user
	has_many :article_categories
	has_many :categories , through: :article_categories

	validates :title , presence:true 
  	validates :description , presence:true
  	
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

	belongs_to :article
	belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord

	has_many :article_categories
	has_many :articles , through: :article_categories

	validates :name , presence: true , length:{ minimum:3 , maximum:25}
	validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord

	before_save {self.email=email.downcase}
	has_many :articles, dependent: :destroy

	validates :username , presence: true , uniqueness: { case_sensitive: false } , length: {minimum: 3 , maximum: 25}
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email , presence: true , length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user
	helper_method :logged_in?

	def current_user

		@current_user ||= User.find(session[:user_id]) if session[:user_id]

	end


	def logged_in?
		!! current_user	
	end

	def require_user
	    if !logged_in?
	      flash[:alert] = "You must be logged in to perform that action"
	      redirect_to login_path
	    end
	  end
end

app/controllers/articles_controller.rb
  class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]  
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
     @article = Article.find(params[:id])
  end

  # POST /articles or /articles.json
  def create
    byebug
    @article = Article.new(article_params)
    @article.user=current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :category_ids )
    end


    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :require_admin, except: [:index, :show]


	def new

		@category = Category.new

	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category is Successfully Created"
			redirect_to @category
		else
			render 'new'

		end

	end

	def index

		@category = Category.paginate(page: params[:page], per_page: 4)

	end

	def show

		@category = Category.find(params[:id])
		@articles = @category.articles.paginate(page: params[:page], per_page: 4)

	end

	def edit
		@category=Category.find(params[:id])

	end

	def update

		@category=Category.find(params[:id])
		if @category.update(category_params)
			flash[:notice]="Category Name updated successfully"
			redirect_to @category

		else
			render 'edit'

		end

	end


	private

	def category_params

		params.require(:category).permit(:name)

	end

	def require_admin

		if !(logged_in? && current_user.admin?)
			flash[:alert]="Only Admins can perfom that Action"
			redirect_to categories_path

		end

	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home 
		redirect_to articles_path if logged_in?
	end

	def about
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user=User.find_by(email: params[:sessions][:email].downcase)
		if user && user.authenticate(params[:sessions][:password])
		session[:user_id]=user.id
		flash[:notice]="You Have Logged in Succesfully to TAL-BLOGS"
		redirect_to users_path

		else
			flash.now[:notice]="OOPS THERE WAS SOMETHING WRONG WITH YOUR LOGIN DETAILS!!"
			render 'new'


		end
	end

	def destroy
		session[:user_id]=nil
		flash[:notice]="You are logged out Succesfully"
		redirect_to root_path
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :require_user, only: [:edit,:update]
before_action :require_same_user, only:[:edit, :update]

	def show
		@user=User.find(params[:id])
		@articles=@user.articles.paginate(page: params[:page], per_page: 4)
	end

	def index

		@users = User.paginate(page: params[:page], per_page: 4)

	end

	def new
		@user = User.new
	end

	def edit
		@user=User.find(params[:id])
	end

	def update

		@user=User.find(params[:id])
		if @user.update(user_params)
			flash[:notice]="Your Account Information is updated successfully"
			redirect_to user_path

		else
			render 'edit'

		end
		
	end


	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id #(this line is written because we want to log the user in when he signup)
			flash[:notice]="Welcome to TAL-BLOGS #{@user.username} , You have signed up successfully!!"
			redirect_to articles_path

		else
			render 'new'
		end

	end

	def destroy
		@user.destroy
		session[:user_id]=nil if @user==current_user
		flash[:notice] ="Account and all asscoiated articles successfully deleted"
		redirect_to articles_path
	end

private 

def user_params

	params.require(:user).permit(:username,:email,:password)

end

def set_user

	@user=User.find(params[:id])

end


def require_same_user

	if current_user != @user && !current_user.admin?
		flash[:alert]="You can edit or delete your own account only!!!"
		redirect_to users_path

	end

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user,options={size:80})

		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		size=options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(gravatar_url, alt:user.username,class:"shadow rounded mx-auto d-block")

	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>

    <div class="row d-flex justify-content-center">
      <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <% if article.user %>
          by <%= link_to article.user.username,user_path(article.user) %>
        <% end %>

        <% if article.categories.any? %>

           <div class="mt-2"><%= render article.categories %></div>

        <% end %>
      </div>
      <div class="card-body">
        <h3 class="card-title"><%= link_to article.title , article_path(article),class:"text-success" %></h3>

        <p class="card-text"><%= truncate(article.description,lenght: 25) %></p>

        <%= link_to 'View',article_path(article) , class:"btn btn-outline-success" %>

        <% if logged_in? && (article.user == current_user || current_user.admin?) %>

        <%= link_to 'Edit',edit_article_path(article) , class:"btn btn-outline-info" %>

        <%= link_to 'Delete',article_path(article),method: :delete , class:"btn btn-outline-danger", data: {confirm:"Are you sure?"} %>

        <% end %>




      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(article.created_at) %> ago
              Updated <%= time_ago_in_words(article.updated_at) %> ago
        </small>
      </div>
    </div>
    </div>
    </div>
    <% end %>
    </div>

app/views/articles/_form.html.erb
<div class="container">  
  <div class="row-2 d-flex justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors',obj: @article %>
      <%= form_with(model:@article , class:"shadow p-3 mb-5 bg-info rounded ") do |form| %>
    <div class="form-group row">
      <%= form.label :title,class:"col-sm-2 col-form-label" %>
          <div class="col-10">
          <%= form.text_field :title,class:"form-control shadow rounded", placeholder: "TITLE OF YOUR ARTICLE" %>
          </div><br/><br/><br/>
    </div>

    <div class="form-group row">
      <%= form.label :description,class:"col-sm-2 col-form-label text-black" %>
        <div class="col-sm-10">
      <%= form.text_area :description, rows: 10 ,class:"form-control shadow rounded",placeholder: "ADD DESCRIPTION HERE" %><br/>
        </div>
    </div><br/>

      <div class="form-group row">
        <%= form.label :Category,class:"col-sm-2 col-form-label text-black" %>
        <div class="col-sm-10">

        <%= form.collection_select(:category_ids,Category.all, :id, :name,class:"mt-4")%>

        </div><br/>
    </div>

    <div class="actions d-flex justify-content-center">
      <%= form.submit class:"btn btn-secondary btn-lg mt-4" %> &nbsp; &nbsp; &nbsp;
    </div>
  <% end %>
    </div>
</div>
</div>


     <div class="actions d-flex justify-content-center">
        <%= link_to 'Return to Article Listing', articles_path ,class:"btn btn-secondary btn-lg text-white" %>
      </div>

app/views/articles/edit.html.erb
<div class="page-content">

	<h1><center>Editing Articles</h1></center>
	<br/><br/>

	<%= render 'form' %>

</div>

app/views/articles/index.html.erb
<div id="page-content">
    <p id="notice">

      </p>

      <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
        </div>


      <%= render 'articles/article'%>

        <div class="flickr_pagination">
            <%= will_paginate @articles, :container => false %>
        </div>


         <center>
          
          <%= link_to 'New Article', new_article_path, class:"btn btn-primary text-white mt-4" %> &nbsp; &nbsp;
          <%= link_to 'Back to home', root_path ,class:"btn btn-success text-white mt-4" %>
        </center>

  </div>

app/views/articles/new.html.erb
<div class="page-content">

	<h1><center>New Article</h1></center>
	<br/><br/>

	<%= render 'form' %>

</div>

app/views/articles/show.html.erb
<div id="show">  
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">

        <div class="card text-center">
          <div class="card-header">
            <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user),user_path(@article.user) %>
              <% if @article.categories.any? %>

                <div class="mt-2"><%= render @article.categories %></div>

              <% end %>

          </div>
          <div class="card-body">
            <h3 class="card-title"><%= @article.title %></h3>
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>

            <% if logged_in? && @article.user == current_user || current_user.admin? %>

              <%= link_to 'Edit', edit_article_path(@article),class:"btn btn-outline-info" %> &nbsp;
              <%= link_to 'Delete', article_path , method: :delete , data: {confirm:"Are you sure?"},class:'btn btn-outline-danger' %>

              <% end %>
            
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago
                Updated <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  </div>
        

app/views/categories/_category.html.erb
<h3><%= link_to category.name , category_path(category) , class: "badge rounded-pill bg-info text-white mt-3 mb-3"%></h3>

app/views/categories/_form.html.erb
 <%= render 'shared/errors',obj: @category %>
      <%= form_with(model:@category , class:"shadow p-3 mb-5 bg-info rounded ") do |form| %>
    <div class="form-group row">
      <%= form.label :name,"Category Name :",class:"col-sm-2 col-form-label" %>
          <div class="col-10">
          <%= form.text_field :name,class:"form-control shadow rounded mb-4",placeholder: "Enter a name" %>
          </div>
    </div>

    <div class="actions d-flex justify-content-center">
      <%= form.submit class:"btn btn-secondary btn-lg mt-4 " %> &nbsp; &nbsp; &nbsp; 
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4"> EDIT CATEGORIES	</h1>

<div class="container">  
  <div class="row-2 d-flex justify-content-center">
    <div class="col-10">
      <%= render 'form'%>
    </div>
</div>
</div>
  <div class="actions d-flex justify-content-center">
    <%= link_to '[ Cancle And Return to Category ]', category_path(@category) ,class:"btn text-success " %>
  </div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories </h1><br/><br/>

	<div class="flickr_pagination">
  		<%= will_paginate @category, :container => false %>
	</div>

	<div class="container">
    	<% @category.each do |category| %>

		    <div class="row d-flex justify-content-center">
		      <div class="col-4 mt-8">
		    <div class="card text-center shadow mb-5 bg-white rounded">
		      <div class="card-body mb-3">
		        <h3 class="card-title"><%= link_to category.name , category_path(category),class:"text-success" %></h3>
		        <p class="card-text"><%= pluralize(category.articles.count,"article") %></p>
		      </div>
		      <div class="card-footer text-muted">
		        <small>Created <%= time_ago_in_words(category.created_at) %> ago
		              Updated <%= time_ago_in_words(category.updated_at) %> ago
		        </small>
		      </div>
		    </div>
		    </div>
		    </div>
		    <% end %>
		    </div>


<div class="flickr_pagination">
  		<%= will_paginate @category, :container => false %>
	</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4"> CREATE CATEGORIES	</h1>

<div class="container">  
  <div class="row-2 d-flex justify-content-center">
    <div class="col-10">
      <%= render 'form'%>
    </div>
</div>
</div>
  <div class="actions d-flex justify-content-center">
    <%= link_to '[ Cancle And Return to Category Listing ]', categories_path ,class:"btn text-success " %>
  </div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name%></h1>

	<% if logged_in? && current_user.admin? %>

		<div class="text-center mt-4">

		<%= link_to "Edit Category Name" , edit_category_path(@category),class:"btn btn btn-outline-info"%>
	</div>

	  <% end %>
		</div>


	<div class="flickr_pagination">
	  <%= will_paginate @articles, :container => false %>
	 </div>
	 
	<%= render 'articles/article' %>


	<div class="flickr_pagination">
	  <%= will_paginate @articles, :container => false %>
	 </div>



	

app/views/layouts/_footer.html.erb
  <br>
  <br><br>
  <footer class="bg-light text-center text-lg-start fixed-bottom",id="footer">
    <!-- Copyright -->
    <div class="text-center p-4 , text-white" style="background-color: rgba(0, 0, 0, 0.7);">
      © 2020 Copyright:
      <a class="text-white" href="https://www.linkedin.com/in/harsh-patel-776198212">H@rsh_P@tel</a>
    </div>
    <!-- Copyright -->
  </footer>

app/views/layouts/_messages.html.erb
<div class="container">	
	<% flash.each do |name,notice| %>

		<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>  alert-dismissible fade show" role="alert">
  		<strong>	<%= notice %>	</strong>
  		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>

		<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
      <%= link_to "TAL-BLOGS",root_path , class:"navbar-brand", id:"logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <%= link_to 'BLOGGERS', users_path , class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

              <% if logged_in? %>
              <%= link_to "Create New Article", new_article_path,class:"dropdown-item" %>

              <% end %>
              <%= link_to "Show Articles", articles_path,class:"dropdown-item" %>
              
            </ul>
          </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                <% if logged_in? && current_user.admin? %>
                <%= link_to "Create New Category", new_category_path,class:"dropdown-item" %>

                <% end %>
                <%= link_to "Show Categories", categories_path,class:"dropdown-item" %>
                
              </ul>
            </li>
          <% if logged_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%="(Admin)" if current_user.admin? %>Profile [<%= current_user.username %>]
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                <%= link_to "View your profile", user_path(current_user),class:"dropdown-item" %>
                <%= link_to "Edit your profile", edit_user_path(current_user),class:"dropdown-item" %>
                <%= link_to "Delete your profile", user_path(current_user),class:"dropdown-item text-danger",method: :delete , data:{confirm: "Are You Sure?"} %>

              </ul>
            </li>

          <li class="nav-item">
            <%= link_to 'LOGOUT', logout_path , class:"nav-link" , method: :delete %>
          </li>

          <% else %>
             <li class="nav-item">
              <%= link_to 'LOGIN', login_path , class:"nav-link" %>
              </li>

              <li class="nav-item">
              <%= link_to 'Signup', signup_path , class:"nav-link" %>
              </li>

          <% end %>
          
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>TAL-BLOGS</title>
  </head>
  <body style="background-color: lightgrey;">
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->

    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;
    &nbsp;

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_home.html.erb
<div id="page-content">
<div class="container" id="homecontainer">
<div class="jumbotron text-center">
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <h1 class="display-4 , text-grey">TAL-BLOGS</h1><br/>
  <p class="lead,text-white"><b><i><h5>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</i></b></p></h5>
  <hr class="my-4">
  <p><h5 class="text-grey">It uses utility classes for typography and spacing to space content out within the larger container.</p></h5><br/><br/>
  <%= link_to "Sign Up!",signup_path , class:"btn btn-success btn-lg ,btn text-white " %>
</div>
</div>
</div>

app/views/pages/about.html.erb
<h1>This is about Page.</h1>

<%= link_to 'Articles Listing',articles_path %>
<%= link_to 'Home Page',root_path %>

app/views/pages/home.html.erb
<div id="page-content">
<div class="container" id="homecontainer">
<div class="jumbotron text-center">
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <h1 class="display-4 , text-grey">TAL-BLOGS</h1><br/>
  <p class="lead,text-white"><b><i><h5>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</i></b></p></h5>
  <hr class="my-4">
  <p><h5 class="text-grey">It uses utility classes for typography and spacing to space content out within the larger container.</p></h5><br/><br/>
  <%= link_to "Sign Up!",signup_path , class:"btn btn-success btn-lg ,btn text-white " %>
</div>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissble fade show" role="alert">
    <div id="error_explanation">
      <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %> from being saved:</h2>

        <ul>
          <% obj.errors.each do |error| %>
          <li><%= error.full_message %></li>
              <% end %>
         </ul>
      </div>
    </div>
  <% end %>

app/views/users/_form.html.erb
<div class="container">  
  <div class="row-2 d-flex justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors',obj: @user %>
      <%= form_with(model:@user , class:"shadow p-3 mb-5 bg-info rounded ") do |form| %>
    <div class="form-group row">
      <%= form.label :username,class:"col-sm-2 col-form-label" %>
          <div class="col-10">
          <%= form.text_field :username,class:"form-control shadow rounded mb-4",placeholder: "Enter a username" %>
          </div>
    </div>

    <div class="form-group row">
      <%= form.label :email,class:"col-sm-2 col-form-label text-black" %>
        <div class="col-sm-10">
      <%= form.email_field :email,class:"form-control shadow rounded mb-4",placeholder: "Enter your Email-Address" %>
        </div>
    </div>

        <div class="form-group row">
          <%= form.label :password,class:"col-sm-2 col-form-label text-black" %>
          <div class="col-sm-10">
          <%= form.password_field :password,class:"form-control shadow rounded",placeholder: "Choose a password" %>
          </div>
    </div><br/>

    <div class="actions d-flex justify-content-center">
      <%= form.submit(@user.new_record? ? "Sign Up!" : "Update account", class:"btn btn-secondary btn-lg mt-4 ") %> &nbsp; &nbsp; &nbsp;
      
    </div>
  <% end %>
    </div>
</div>
</div>
  <div class="actions d-flex justify-content-center">
    <%= link_to 'Return to Article Listing', articles_path ,class:"btn btn-secondary btn-lg text-white" %>
  </div>

app/views/users/edit.html.erb
<div class="page-content">

	<h1><center>Edit your Profile</h1></center>
	<br/><br/>

	<%= render 'form' %>

</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> TAL-BLOGGERS	</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

	<div class="container">
    <% @users.each do |user| %>

    <div class="row d-flex justify-content-center">
      <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header">
        <%= link_to user.username,user_path(user) %>
      </div>
      <div class="card-body">
        <h3 class="card-title"><%= link_to gravatar_for(user,size: 150),user_path(user) %></h3>
        <p class="card-text"><%= pluralize(user.articles.count,"article") %></p>

        <%= link_to 'View Profile',user_path(user) , class:"btn btn-outline-success" %>

        <% if logged_in? %>

          <% if user==current_user %>

          <%= link_to 'Edit Profile',edit_user_path(user) , class:"btn btn-outline-info" %>

        <% end %>

        <% if current_user.admin? %>

          <%= link_to "Delete Profile",user_path(user),class:"btn btn-danger text-white",method: :delete,data:{confirm: "ARE YOU SURE YOU WANT TO DELTE THIS USER ACCOUNT"}%>

        <% end %>

        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at) %> ago
        </small>
      </div>
    </div>
    </div>
    </div>
    <% end %>
    </div>

    <div class="flickr_pagination">
      <%= will_paginate @users, :container => false %>
    </div>

app/views/users/new.html.erb
<div class="page-content">

	<h1><center>SIGN UP FOR BLOGS</h1></center>
	<br/><br/>

	<%= render 'form' %>

</div>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username%>'s profile</h1>

<%= gravatar_for @user, size:300 %>

<h3 class="text-center mt-4">Articles</h3>

<div class="text-center mt-4">

  <% if logged_in? && @user==current_user %>

	<%= link_to "Edit your Profile" , edit_user_path,class:"btn btn btn-outline-info"%>

  <% end %>
	</div>


<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
 </div>
 
<%= render 'articles/article' %>


<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
 </div>